// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFxySmO0h3d12PiosbU-UCXDDOC5PLE70',
    appId: '1:771816894798:web:da87317d8678d12cdf6e1f',
    messagingSenderId: '771816894798',
    projectId: 'royal-app-fundas-2026-py-6d3c9',
    authDomain: 'royal-app-fundas-2026-py-6d3c9.firebaseapp.com',
    storageBucket: 'royal-app-fundas-2026-py-6d3c9.firebasestorage.app',
    measurementId: 'G-YG30LGHQ37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkrUAmagZY_d4q0HZLJi1xawoFU09fOu0',
    appId: '1:771816894798:android:1f9181ba06dbfaccdf6e1f',
    messagingSenderId: '771816894798',
    projectId: 'royal-app-fundas-2026-py-6d3c9',
    storageBucket: 'royal-app-fundas-2026-py-6d3c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQYV_rXzwyFOSE9vYRvb29LDQ8Zs6YKTo',
    appId: '1:771816894798:ios:4b185d698054e80bdf6e1f',
    messagingSenderId: '771816894798',
    projectId: 'royal-app-fundas-2026-py-6d3c9',
    storageBucket: 'royal-app-fundas-2026-py-6d3c9.firebasestorage.app',
    iosBundleId: 'com.example.royalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQYV_rXzwyFOSE9vYRvb29LDQ8Zs6YKTo',
    appId: '1:771816894798:ios:4b185d698054e80bdf6e1f',
    messagingSenderId: '771816894798',
    projectId: 'royal-app-fundas-2026-py-6d3c9',
    storageBucket: 'royal-app-fundas-2026-py-6d3c9.firebasestorage.app',
    iosBundleId: 'com.example.royalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFxySmO0h3d12PiosbU-UCXDDOC5PLE70',
    appId: '1:771816894798:web:9956b2a1c4bc3ba7df6e1f',
    messagingSenderId: '771816894798',
    projectId: 'royal-app-fundas-2026-py-6d3c9',
    authDomain: 'royal-app-fundas-2026-py-6d3c9.firebaseapp.com',
    storageBucket: 'royal-app-fundas-2026-py-6d3c9.firebasestorage.app',
    measurementId: 'G-9VD6CKKZ91',
  );
}
