// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf2aDGyqNQYbygayCFnp8k3Q7lvPzdddc',
    appId: '1:381998098827:web:8b27d66dd428249630278e',
    messagingSenderId: '381998098827',
    projectId: 'royal-3ceec',
    authDomain: 'royal-3ceec.firebaseapp.com',
    storageBucket: 'royal-3ceec.firebasestorage.app',
    measurementId: 'G-88G6QS8X0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9dp4D5pWfTx4YZujjwbJVSAfu8Dp19nE',
    appId: '1:381998098827:android:bd58d0a65a85a4a830278e',
    messagingSenderId: '381998098827',
    projectId: 'royal-3ceec',
    storageBucket: 'royal-3ceec.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcuGfclSas_e74MsPrUGLwiWoLWNOlh5w',
    appId: '1:381998098827:ios:366c5b4a7f25845430278e',
    messagingSenderId: '381998098827',
    projectId: 'royal-3ceec',
    storageBucket: 'royal-3ceec.firebasestorage.app',
    iosBundleId: 'com.example.royalApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcuGfclSas_e74MsPrUGLwiWoLWNOlh5w',
    appId: '1:381998098827:ios:366c5b4a7f25845430278e',
    messagingSenderId: '381998098827',
    projectId: 'royal-3ceec',
    storageBucket: 'royal-3ceec.firebasestorage.app',
    iosBundleId: 'com.example.royalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf2aDGyqNQYbygayCFnp8k3Q7lvPzdddc',
    appId: '1:381998098827:web:71b767a5e39a8cae30278e',
    messagingSenderId: '381998098827',
    projectId: 'royal-3ceec',
    authDomain: 'royal-3ceec.firebaseapp.com',
    storageBucket: 'royal-3ceec.firebasestorage.app',
    measurementId: 'G-84QJMK7VFH',
  );
}
